#!/bin/bash
set -e

lb config noauto \
    --architecture amd64 \
    --distribution trixie \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap http://deb.debian.org/debian/ \
    --mirror-chroot http://deb.debian.org/debian/ \
    --mirror-chroot-security http://security.debian.org/debian-security/ \
    --mirror-binary http://deb.debian.org/debian/ \
    --mirror-binary-security http://security.debian.org/debian-security/ \
    --linux-packages "linux-image" \
    --linux-flavours "amd64" \
    --firmware-chroot false \
    --firmware-binary false \
    --debian-installer false \
    --binary-images iso-hybrid \
    --bootloader "grub-efi" \
    --memtest none \
    --win32-loader false \
    --apt-recommends false \
    --iso-volume "FellowshipOS" \
    --iso-publisher "Chris" \
    --iso-application "FellowshipOS Base"
